logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true