spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_schedules?serverTimezone=Asia/Seoul
    username: root
    password: 0000

  jpa:
    hibernate:
      ddl-auto: validate