name: Build and Push Docker Image

on: 
  workflow_dispatch:
    inputs: 
      server_version:
        description: 'Server version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 297606574770.dkr.ecr.ap-northeast-2.amazonaws.com/travel
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Grant execute permission for gradlew
      run:  cd travelSchedules && chmod +x gradlew

    - name: Build and Push Docker Image
      run: |
         cd travelSchedules && ./gradlew jib -Djib.to.image=${{ secrets.ECR_URL }} -Pversion=${{ github.event.inputs.server_version }}
